/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq;


import io.github.marcelothebuilder.restbooks.jooq.tables.Autor;
import io.github.marcelothebuilder.restbooks.jooq.tables.Comentario;
import io.github.marcelothebuilder.restbooks.jooq.tables.Livro;
import io.github.marcelothebuilder.restbooks.jooq.tables.records.AutorRecord;
import io.github.marcelothebuilder.restbooks.jooq.tables.records.ComentarioRecord;
import io.github.marcelothebuilder.restbooks.jooq.tables.records.LivroRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<AutorRecord, Long> IDENTITY_AUTOR = Identities0.IDENTITY_AUTOR;
	public static final Identity<LivroRecord, Long> IDENTITY_LIVRO = Identities0.IDENTITY_LIVRO;
	public static final Identity<ComentarioRecord, Long> IDENTITY_COMENTARIO = Identities0.IDENTITY_COMENTARIO;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AutorRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
	public static final UniqueKey<LivroRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
	public static final UniqueKey<ComentarioRecord> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<LivroRecord, AutorRecord> FK_LIVRO_AUTOR = ForeignKeys0.FK_LIVRO_AUTOR;
	public static final ForeignKey<ComentarioRecord, LivroRecord> FK_COMENTARIO_LIVRO = ForeignKeys0.FK_COMENTARIO_LIVRO;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<AutorRecord, Long> IDENTITY_AUTOR = createIdentity(Autor.AUTOR, Autor.AUTOR.CODIGO);
		public static Identity<LivroRecord, Long> IDENTITY_LIVRO = createIdentity(Livro.LIVRO, Livro.LIVRO.CODIGO);
		public static Identity<ComentarioRecord, Long> IDENTITY_COMENTARIO = createIdentity(Comentario.COMENTARIO, Comentario.COMENTARIO.CODIGO);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AutorRecord> CONSTRAINT_3 = createUniqueKey(Autor.AUTOR, Autor.AUTOR.CODIGO);
		public static final UniqueKey<LivroRecord> CONSTRAINT_4 = createUniqueKey(Livro.LIVRO, Livro.LIVRO.CODIGO);
		public static final UniqueKey<ComentarioRecord> CONSTRAINT_B = createUniqueKey(Comentario.COMENTARIO, Comentario.COMENTARIO.CODIGO);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<LivroRecord, AutorRecord> FK_LIVRO_AUTOR = createForeignKey(io.github.marcelothebuilder.restbooks.jooq.Keys.CONSTRAINT_3, Livro.LIVRO, Livro.LIVRO.CODIGO_AUTOR);
		public static final ForeignKey<ComentarioRecord, LivroRecord> FK_COMENTARIO_LIVRO = createForeignKey(io.github.marcelothebuilder.restbooks.jooq.Keys.CONSTRAINT_4, Comentario.COMENTARIO, Comentario.COMENTARIO.CODIGO_LIVRO);
	}
}
