/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq;


import io.github.marcelothebuilder.restbooks.jooq.tables.Autor;
import io.github.marcelothebuilder.restbooks.jooq.tables.Comentario;
import io.github.marcelothebuilder.restbooks.jooq.tables.Livro;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

	private static final long serialVersionUID = 1427969466;

	/**
	 * The reference instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final List<Sequence<?>> getSequences() {
		List result = new ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final List<Sequence<?>> getSequences0() {
		return Arrays.<Sequence<?>>asList(
			Sequences.SYSTEM_SEQUENCE_1D337E24_84AF_4AE9_946D_DDDD5A484FB1,
			Sequences.SYSTEM_SEQUENCE_51D7F7B3_DDB3_4B1B_B997_399ED55BB197,
			Sequences.SYSTEM_SEQUENCE_73B0B086_4B33_47B5_8D22_F08D3CE8A3F8);
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Autor.AUTOR,
			Livro.LIVRO,
			Comentario.COMENTARIO);
	}
}
