/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_58CF8774_5262_4328_B30D_3407D59F1023</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_58CF8774_5262_4328_B30D_3407D59F1023 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_58CF8774_5262_4328_B30D_3407D59F1023", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_C91FE864_66FC_42E8_A874_94F1F37DFBED</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_C91FE864_66FC_42E8_A874_94F1F37DFBED = new SequenceImpl<Long>("SYSTEM_SEQUENCE_C91FE864_66FC_42E8_A874_94F1F37DFBED", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_D33D889E_91E4_44D9_B316_351195ED953A</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_D33D889E_91E4_44D9_B316_351195ED953A = new SequenceImpl<Long>("SYSTEM_SEQUENCE_D33D889E_91E4_44D9_B316_351195ED953A", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
