/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_1D337E24_84AF_4AE9_946D_DDDD5A484FB1</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_1D337E24_84AF_4AE9_946D_DDDD5A484FB1 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_1D337E24_84AF_4AE9_946D_DDDD5A484FB1", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_51D7F7B3_DDB3_4B1B_B997_399ED55BB197</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_51D7F7B3_DDB3_4B1B_B997_399ED55BB197 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_51D7F7B3_DDB3_4B1B_B997_399ED55BB197", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_73B0B086_4B33_47B5_8D22_F08D3CE8A3F8</code>
	 */
	public static final Sequence<Long> SYSTEM_SEQUENCE_73B0B086_4B33_47B5_8D22_F08D3CE8A3F8 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_73B0B086_4B33_47B5_8D22_F08D3CE8A3F8", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
