/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq;


import io.github.marcelothebuilder.restbooks.jooq.tables.Comentario;
import io.github.marcelothebuilder.restbooks.jooq.tables.Livro;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.LIVRO
	 */
	public static final Livro LIVRO = io.github.marcelothebuilder.restbooks.jooq.tables.Livro.LIVRO;

	/**
	 * The table PUBLIC.COMENTARIO
	 */
	public static final Comentario COMENTARIO = io.github.marcelothebuilder.restbooks.jooq.tables.Comentario.COMENTARIO;
}
