/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq;


import io.github.marcelothebuilder.restbooks.jooq.tables.Autor;
import io.github.marcelothebuilder.restbooks.jooq.tables.Comentario;
import io.github.marcelothebuilder.restbooks.jooq.tables.Livro;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.AUTOR
	 */
	public static final Autor AUTOR = io.github.marcelothebuilder.restbooks.jooq.tables.Autor.AUTOR;

	/**
	 * The table PUBLIC.LIVRO
	 */
	public static final Livro LIVRO = io.github.marcelothebuilder.restbooks.jooq.tables.Livro.LIVRO;

	/**
	 * The table PUBLIC.COMENTARIO
	 */
	public static final Comentario COMENTARIO = io.github.marcelothebuilder.restbooks.jooq.tables.Comentario.COMENTARIO;
}
