/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comentario implements Serializable {

	private static final long serialVersionUID = 425020130;

	private Long   codigo;
	private Long   codigoLivro;
	private String autor;
	private String conteudo;

	public Comentario() {}

	public Comentario(Comentario value) {
		this.codigo = value.codigo;
		this.codigoLivro = value.codigoLivro;
		this.autor = value.autor;
		this.conteudo = value.conteudo;
	}

	public Comentario(
		Long   codigo,
		Long   codigoLivro,
		String autor,
		String conteudo
	) {
		this.codigo = codigo;
		this.codigoLivro = codigoLivro;
		this.autor = autor;
		this.conteudo = conteudo;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public Long getCodigoLivro() {
		return this.codigoLivro;
	}

	public void setCodigoLivro(Long codigoLivro) {
		this.codigoLivro = codigoLivro;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public String getConteudo() {
		return this.conteudo;
	}

	public void setConteudo(String conteudo) {
		this.conteudo = conteudo;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Comentario (");

		sb.append(codigo);
		sb.append(", ").append(codigoLivro);
		sb.append(", ").append(autor);
		sb.append(", ").append(conteudo);

		sb.append(")");
		return sb.toString();
	}
}
