/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Livro implements Serializable {

	private static final long serialVersionUID = 1540509851;

	private Long      codigo;
	private String    nome;
	private Timestamp publicacao;
	private String    editora;
	private String    resumo;
	private String    autor;

	public Livro() {}

	public Livro(Livro value) {
		this.codigo = value.codigo;
		this.nome = value.nome;
		this.publicacao = value.publicacao;
		this.editora = value.editora;
		this.resumo = value.resumo;
		this.autor = value.autor;
	}

	public Livro(
		Long      codigo,
		String    nome,
		Timestamp publicacao,
		String    editora,
		String    resumo,
		String    autor
	) {
		this.codigo = codigo;
		this.nome = nome;
		this.publicacao = publicacao;
		this.editora = editora;
		this.resumo = resumo;
		this.autor = autor;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Timestamp getPublicacao() {
		return this.publicacao;
	}

	public void setPublicacao(Timestamp publicacao) {
		this.publicacao = publicacao;
	}

	public String getEditora() {
		return this.editora;
	}

	public void setEditora(String editora) {
		this.editora = editora;
	}

	public String getResumo() {
		return this.resumo;
	}

	public void setResumo(String resumo) {
		this.resumo = resumo;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Livro (");

		sb.append(codigo);
		sb.append(", ").append(nome);
		sb.append(", ").append(publicacao);
		sb.append(", ").append(editora);
		sb.append(", ").append(resumo);
		sb.append(", ").append(autor);

		sb.append(")");
		return sb.toString();
	}
}
