/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq.tables;


import io.github.marcelothebuilder.restbooks.jooq.Keys;
import io.github.marcelothebuilder.restbooks.jooq.Public;
import io.github.marcelothebuilder.restbooks.jooq.tables.records.ComentarioRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comentario extends TableImpl<ComentarioRecord> {

	private static final long serialVersionUID = 306934366;

	/**
	 * The reference instance of <code>PUBLIC.COMENTARIO</code>
	 */
	public static final Comentario COMENTARIO = new Comentario();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ComentarioRecord> getRecordType() {
		return ComentarioRecord.class;
	}

	/**
	 * The column <code>PUBLIC.COMENTARIO.CODIGO</code>.
	 */
	public final TableField<ComentarioRecord, Long> CODIGO = createField("CODIGO", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.COMENTARIO.CODIGO_LIVRO</code>.
	 */
	public final TableField<ComentarioRecord, Long> CODIGO_LIVRO = createField("CODIGO_LIVRO", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.COMENTARIO.AUTOR</code>.
	 */
	public final TableField<ComentarioRecord, String> AUTOR = createField("AUTOR", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.COMENTARIO.CONTEUDO</code>.
	 */
	public final TableField<ComentarioRecord, String> CONTEUDO = createField("CONTEUDO", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.COMENTARIO.DATA</code>.
	 */
	public final TableField<ComentarioRecord, Timestamp> DATA = createField("DATA", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>PUBLIC.COMENTARIO</code> table reference
	 */
	public Comentario() {
		this("COMENTARIO", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.COMENTARIO</code> table reference
	 */
	public Comentario(String alias) {
		this(alias, COMENTARIO);
	}

	private Comentario(String alias, Table<ComentarioRecord> aliased) {
		this(alias, aliased, null);
	}

	private Comentario(String alias, Table<ComentarioRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<ComentarioRecord, Long> getIdentity() {
		return Keys.IDENTITY_COMENTARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ComentarioRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_B;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ComentarioRecord>> getKeys() {
		return Arrays.<UniqueKey<ComentarioRecord>>asList(Keys.CONSTRAINT_B);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ComentarioRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ComentarioRecord, ?>>asList(Keys.FK_COMENTARIO_LIVRO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Comentario as(String alias) {
		return new Comentario(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Comentario rename(String name) {
		return new Comentario(name, null);
	}
}
