/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq.tables.records;


import io.github.marcelothebuilder.restbooks.jooq.tables.Comentario;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ComentarioRecord extends UpdatableRecordImpl<ComentarioRecord> implements Record5<Long, Long, String, String, Timestamp> {

	private static final long serialVersionUID = -1935214277;

	/**
	 * Setter for <code>PUBLIC.COMENTARIO.CODIGO</code>.
	 */
	public void setCodigo(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMENTARIO.CODIGO</code>.
	 */
	public Long getCodigo() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.COMENTARIO.CODIGO_LIVRO</code>.
	 */
	public void setCodigoLivro(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMENTARIO.CODIGO_LIVRO</code>.
	 */
	public Long getCodigoLivro() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.COMENTARIO.AUTOR</code>.
	 */
	public void setAutor(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMENTARIO.AUTOR</code>.
	 */
	public String getAutor() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.COMENTARIO.CONTEUDO</code>.
	 */
	public void setConteudo(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMENTARIO.CONTEUDO</code>.
	 */
	public String getConteudo() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.COMENTARIO.DATA</code>.
	 */
	public void setData(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMENTARIO.DATA</code>.
	 */
	public Timestamp getData() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Long, String, String, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, Long, String, String, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Comentario.COMENTARIO.CODIGO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return Comentario.COMENTARIO.CODIGO_LIVRO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Comentario.COMENTARIO.AUTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Comentario.COMENTARIO.CONTEUDO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Comentario.COMENTARIO.DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getCodigo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getCodigoLivro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAutor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getConteudo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord value1(Long value) {
		setCodigo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord value2(Long value) {
		setCodigoLivro(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord value3(String value) {
		setAutor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord value4(String value) {
		setConteudo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord value5(Timestamp value) {
		setData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord values(Long value1, Long value2, String value3, String value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ComentarioRecord
	 */
	public ComentarioRecord() {
		super(Comentario.COMENTARIO);
	}

	/**
	 * Create a detached, initialised ComentarioRecord
	 */
	public ComentarioRecord(Long codigo, Long codigoLivro, String autor, String conteudo, Timestamp data) {
		super(Comentario.COMENTARIO);

		setValue(0, codigo);
		setValue(1, codigoLivro);
		setValue(2, autor);
		setValue(3, conteudo);
		setValue(4, data);
	}
}
