/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq.tables.records;


import io.github.marcelothebuilder.restbooks.jooq.tables.Comentario;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ComentarioRecord extends UpdatableRecordImpl<ComentarioRecord> implements Record4<Long, Long, String, String> {

	private static final long serialVersionUID = 644997910;

	/**
	 * Setter for <code>PUBLIC.COMENTARIO.CODIGO</code>.
	 */
	public void setCodigo(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMENTARIO.CODIGO</code>.
	 */
	public Long getCodigo() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.COMENTARIO.CODIGO_LIVRO</code>.
	 */
	public void setCodigoLivro(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMENTARIO.CODIGO_LIVRO</code>.
	 */
	public Long getCodigoLivro() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.COMENTARIO.AUTOR</code>.
	 */
	public void setAutor(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMENTARIO.AUTOR</code>.
	 */
	public String getAutor() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.COMENTARIO.CONTEUDO</code>.
	 */
	public void setConteudo(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.COMENTARIO.CONTEUDO</code>.
	 */
	public String getConteudo() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, String, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Long, Long, String, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Comentario.COMENTARIO.CODIGO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return Comentario.COMENTARIO.CODIGO_LIVRO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Comentario.COMENTARIO.AUTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Comentario.COMENTARIO.CONTEUDO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getCodigo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getCodigoLivro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAutor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getConteudo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord value1(Long value) {
		setCodigo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord value2(Long value) {
		setCodigoLivro(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord value3(String value) {
		setAutor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord value4(String value) {
		setConteudo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ComentarioRecord values(Long value1, Long value2, String value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ComentarioRecord
	 */
	public ComentarioRecord() {
		super(Comentario.COMENTARIO);
	}

	/**
	 * Create a detached, initialised ComentarioRecord
	 */
	public ComentarioRecord(Long codigo, Long codigoLivro, String autor, String conteudo) {
		super(Comentario.COMENTARIO);

		setValue(0, codigo);
		setValue(1, codigoLivro);
		setValue(2, autor);
		setValue(3, conteudo);
	}
}
