/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq.tables.records;


import io.github.marcelothebuilder.restbooks.jooq.tables.Livro;

import java.sql.Date;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LivroRecord extends UpdatableRecordImpl<LivroRecord> implements Record6<Long, String, Date, String, String, Long> {

	private static final long serialVersionUID = 211108309;

	/**
	 * Setter for <code>PUBLIC.LIVRO.CODIGO</code>.
	 */
	public void setCodigo(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.CODIGO</code>.
	 */
	public Long getCodigo() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.LIVRO.NOME</code>.
	 */
	public void setNome(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.NOME</code>.
	 */
	public String getNome() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.LIVRO.PUBLICACAO</code>.
	 */
	public void setPublicacao(Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.PUBLICACAO</code>.
	 */
	public Date getPublicacao() {
		return (Date) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.LIVRO.EDITORA</code>.
	 */
	public void setEditora(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.EDITORA</code>.
	 */
	public String getEditora() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.LIVRO.RESUMO</code>.
	 */
	public void setResumo(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.RESUMO</code>.
	 */
	public String getResumo() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.LIVRO.CODIGO_AUTOR</code>.
	 */
	public void setCodigoAutor(Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.CODIGO_AUTOR</code>.
	 */
	public Long getCodigoAutor() {
		return (Long) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, String, Date, String, String, Long> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, String, Date, String, String, Long> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Livro.LIVRO.CODIGO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Livro.LIVRO.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field3() {
		return Livro.LIVRO.PUBLICACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Livro.LIVRO.EDITORA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Livro.LIVRO.RESUMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return Livro.LIVRO.CODIGO_AUTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getCodigo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value3() {
		return getPublicacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getEditora();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getResumo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getCodigoAutor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value1(Long value) {
		setCodigo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value2(String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value3(Date value) {
		setPublicacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value4(String value) {
		setEditora(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value5(String value) {
		setResumo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value6(Long value) {
		setCodigoAutor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord values(Long value1, String value2, Date value3, String value4, String value5, Long value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LivroRecord
	 */
	public LivroRecord() {
		super(Livro.LIVRO);
	}

	/**
	 * Create a detached, initialised LivroRecord
	 */
	public LivroRecord(Long codigo, String nome, Date publicacao, String editora, String resumo, Long codigoAutor) {
		super(Livro.LIVRO);

		setValue(0, codigo);
		setValue(1, nome);
		setValue(2, publicacao);
		setValue(3, editora);
		setValue(4, resumo);
		setValue(5, codigoAutor);
	}
}
