/**
 * This class is generated by jOOQ
 */
package io.github.marcelothebuilder.restbooks.jooq.tables.records;


import io.github.marcelothebuilder.restbooks.jooq.tables.Livro;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LivroRecord extends UpdatableRecordImpl<LivroRecord> implements Record6<Long, String, Timestamp, String, String, String> {

	private static final long serialVersionUID = 650241897;

	/**
	 * Setter for <code>PUBLIC.LIVRO.CODIGO</code>.
	 */
	public void setCodigo(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.CODIGO</code>.
	 */
	public Long getCodigo() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.LIVRO.NOME</code>.
	 */
	public void setNome(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.NOME</code>.
	 */
	public String getNome() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>PUBLIC.LIVRO.PUBLICACAO</code>.
	 */
	public void setPublicacao(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.PUBLICACAO</code>.
	 */
	public Timestamp getPublicacao() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>PUBLIC.LIVRO.EDITORA</code>.
	 */
	public void setEditora(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.EDITORA</code>.
	 */
	public String getEditora() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>PUBLIC.LIVRO.RESUMO</code>.
	 */
	public void setResumo(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.RESUMO</code>.
	 */
	public String getResumo() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>PUBLIC.LIVRO.AUTOR</code>.
	 */
	public void setAutor(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>PUBLIC.LIVRO.AUTOR</code>.
	 */
	public String getAutor() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, String, Timestamp, String, String, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, String, Timestamp, String, String, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Livro.LIVRO.CODIGO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Livro.LIVRO.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Livro.LIVRO.PUBLICACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Livro.LIVRO.EDITORA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Livro.LIVRO.RESUMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Livro.LIVRO.AUTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getCodigo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getPublicacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getEditora();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getResumo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getAutor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value1(Long value) {
		setCodigo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value2(String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value3(Timestamp value) {
		setPublicacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value4(String value) {
		setEditora(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value5(String value) {
		setResumo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord value6(String value) {
		setAutor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LivroRecord values(Long value1, String value2, Timestamp value3, String value4, String value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LivroRecord
	 */
	public LivroRecord() {
		super(Livro.LIVRO);
	}

	/**
	 * Create a detached, initialised LivroRecord
	 */
	public LivroRecord(Long codigo, String nome, Timestamp publicacao, String editora, String resumo, String autor) {
		super(Livro.LIVRO);

		setValue(0, codigo);
		setValue(1, nome);
		setValue(2, publicacao);
		setValue(3, editora);
		setValue(4, resumo);
		setValue(5, autor);
	}
}
